### ISSUE TITLE
TypeError: 'QByteArray' does not have the buffer interface

### ISSUE THREAD

**Issue by tolotrasamuel** [djfun/audio-visualizer-python#51]
1. I don't get the preview. 
2. And I am not able to create the video. 
This error appears for the events mentioned above.

```
Traceback (most recent call last):
  File "C:\Users\Tolotra Samuel\PycharmProjects\toysong\audio-visualizer-python-master\preview_thread.py", line 67, in process
    nextPreviewInformation["visColor"])
  File "C:\Users\Tolotra Samuel\PycharmProjects\toysong\audio-visualizer-python-master\core.py", line 86, in drawBaseImage
    strio.write(buffer.data())
TypeError: 'QByteArray' does not have the buffer interface

```

**Comment by tassaron2** [comment]
Thank you for the bug report, but you're using the `master` branch version which is no longer being developed. Therefore I'm going to close this issue. I recommend you use the next version of the program instead, which is in the `feature-newgui` branch. It's nearly a complete rewrite and uses Qt5 instead of Qt4.

Open a new issue if you have trouble running the newgui branch.
